# Generated by Django 2.2.13 on 2020-07-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('concurrency', models.IntegerField(default=1)),
                ('download_dir', models.CharField(max_length=1000)),
                ('shape_file_path', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
                ('platformname', models.CharField(max_length=50)),
                ('satname', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('data_time', models.DateTimeField()),
                ('product_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Download Started'), ('queued', 'Download is Yet to start'), ('error', 'Download stopped because of error'), ('finished', 'Download is finished')], max_length=50)),
                ('download_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copernicus.DownloadProfile')),
            ],
        ),
    ]
