# Generated by Django 2.2.13 on 2020-07-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copernicus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadprofile',
            name='satellite_name',
            field=models.CharField(default='Sentinel-1', max_length=50),
        ),
    ]
