# Generated by Django 2.2.13 on 2020-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copernicus', '0002_downloadprofile_satellite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadprofile',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='downloadprofile',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='data_time',
            field=models.DateField(),
        ),
    ]
