# Generated by Django 2.2.13 on 2020-07-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copernicus', '0003_auto_20200704_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadprofile',
            name='end_date',
            field=models.DateField(),
        ),
    ]
