# Generated by Django 2.2.13 on 2020-07-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copernicus', '0005_auto_20200704_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadprofile',
            name='satellite_name',
            field=models.CharField(default='Sentinel-1', max_length=50),
        ),
    ]
