# Generated by Django 2.2.13 on 2020-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copernicus', '0006_auto_20200704_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadprofile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='downloadprofile',
            name='start_date',
        ),
        migrations.AddField(
            model_name='downloadprofile',
            name='daysdiff',
            field=models.IntegerField(default=3),
        ),
    ]
