# Generated by Django 2.2.13 on 2020-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copernicus', '0007_auto_20200704_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadprofile',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='queue_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='satellite_name',
            field=models.CharField(default='Sentinel-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='product_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
